change desc

diff --git a/.github/workflows/building.yml b/.github/workflows/building.yml
--- a/.github/workflows/building.yml
+++ b/.github/workflows/building.yml
@@ -3,6 +3,9 @@ name: Upload Homebrew Bottles
 on:
   pull_request:
 
+env:
+  SEMVER_REGEX: "^([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$"
+
 jobs:
   release:
     runs-on: ubuntu-latest
@@ -11,15 +14,24 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v2
+      
+      - name: Attempt to get version from latest commit message
+        shell: bash
+        run: |
+          echo VERSION=$(echo "${{ github.event.head_commit.message }}" | sed 's/${{ env.SEMVER_REGEX }}/\1/') >> $GITHUB_ENV
+          if [ "${{ env.VERSION }}" == '' ]; then
+              echo "Unable to parse version for release from latest commit message";
+          fi
+          exit 1
 
-      - name: Create a new release
+      - name: Create a new release 
         id: create_release
         uses: actions/create-release@v1
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
-          tag_name: ${{ github.ref_name }}
-          release_name: Release ${{ github.ref_name }}
+          tag_name: ${{ env.Version }}
+          release_name: Release ${{ env.Version }}
           draft: false
           prerelease: false
 
@@ -51,5 +63,5 @@ jobs:
         with: 
           upload_url: ${{ needs.release.outputs.upload_url }}
           asset_path: ${{ env.BOTTLE_FILEPATH }}
-          asset_name: ${{ env.BOTTLE_FILENAME }}
+          asset_name: ${{ env.BOTTLE_FILEPATH }} # need to change to env.BOTTLE_FILENAME when I figure out how to get that working
           asset_content_type: application/gzip
